### ISSUE TITLE
about dataset 

### ISSUE THREAD

**Issue by yaru-zhang** [VITA-Group/AGD#10]
Hi, author!
I have noticed that the uploaded datasets have been moved to the Trash.
Would you mind uploading them again?
![image](https://user-images.githubusercontent.com/40425823/97101414-343b9880-16d8-11eb-91ec-aea84327dc5f.png)

Thanks a lot.

**Comment by tilmto** [comment]
Hi, the original link is from a third-party drive and it seems that they delete it. I have uploaded it in a new drive and you can check it in the updated ReadMe.

**Comment by yaru-zhang** [comment]
Thanks a lot for your quick reply!

**Comment by yaru-zhang** [comment]
Please upload another SR-training-dataset, thank you~

**Comment by tilmto** [comment]
All the datasets are public datasets and you can refer to https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#DIV2K.
