### ISSUE TITLE
what's Beta means?

### ISSUE THREAD

**Issue by EliteBeastSlamor** [VITA-Group/AGD#5]
Hi, author!
I have noticed that there are variables called 'beta' in your code, but it seems that they are set zero in the whole process. Would you mind tell me what it means?

**Comment by tilmto** [comment]
Yes, the beta is never used in the current version. Originally it's used to control whether to quantize the layer to 8 bit.

**Comment by EliteBeastSlamor** [comment]
thanks a lot
